version: '2'
services:
  homs:
    image: homs2020:1.1
    ports: 
      - "8081:8081"
      - "8082:8082"
    command: bash -c "service mysql start && python3.7 /homs/homs_run.py -port=8081 -ws-port=8082"
    container_name: homs2020
    tty: true